export const SHOW_ALERT = 'SHOW_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const REQUEST_BEGIN = 'REQUEST_BEGIN';

export const OPEN_SIDEBAR_MODAL = 'OPEN_SIDEBAR_MODAL';
export const CLOSE_SIDEBAR_MODAL = 'CLOSE_SIDEBAR_MODAL';

export const USER_REGISTER_BEGIN = 'USER_REGISTER_BEGIN';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED';

export const USER_LOGIN_BEGIN = 'USER_LOGIN_BEGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';

export const USER_UPDATE_BEGIN = 'USER_UPDATE_BEGIN';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAILED = 'USER_UPDATE_FAILED';

// export const GOAL_CREATE_BEGIN = 'GOAL_CREATE_BEGIN';
export const GOAL_CREATE_SUCCESS = 'GOAl_CREATE_BEGIN';
export const GOAL_CREATE_FAILED = 'GOAL_CREATE_FAILED';
